export const STEP_S = 0.05
export const AUTOSAVE_MS = 10_000
export const SAVE_KEY = 'comfy-clicker:save'
export const SAVE_VERSION = 1
/** In-game "week" length for trending hashtags. */
export const WEEK_MS = 10 * 60_000
export const TRENDING_COUNT = 3
export const TRENDING_WEIGHTS = [1.0, 0.4] as const
export const MAX_MATCHED_TRENDING = 2
export const EXTRA_KEYWORD_BONUS = 0.1
export const MAX_EXTRA_KEYWORDS = 3
export const REPOST_PENALTY = 0.5
export const POST_WINDOW_MS = 8_000
export const MAX_POSTS = 60
export const MAX_QUEUE = 8
export const GEN_TIME_MIN_S = 3
export const GEN_TIME_MAX_S = 15
export const TIER_DELTA_FACTOR = 1.3
export const ABOVE_TIER_FACTOR = 0.85
export const CLICK_JOB_BONUS_MS = 150
export const CLICK_JOB_BONUS_CAP = 0.5
export const OFFLINE_CAP_HOURS_BASE = 12
export const OFFLINE_EFFICIENCY = 1
export const SHORT_GAP_S = 300
export const POWER_BUDGET_BASE = 650
export const POWER_THROTTLE = 0.5
export const SETUP_FEE_MULT = 5
export const SIGNUP_THRESHOLDS = [0, 100, 250, 500, 1_000, 2_500, 5_000, 10_000, 25_000, 50_000, 100_000]
export const SIGNUP_GROWTH = 2
export const FOLLOW_RATE_BASE = 0.05
export const VIRAL_FOLLOW_MULT = 3
export const VIRAL_CHANCE_BASE = 0.05
export const FLOP_CHANCE_BASE = 0.15
export const FOUNDER_BOOST_CHANCE = 0.02
export const AUDIENCE_REF_DIVISOR = 50
export const CONTRACT_SLOTS = 3
export const CONTRACT_ROTATE_MS = 30 * 60_000
export const EVENT_MIN_GAP_MS = 3 * 60_000
export const EVENT_MAX_GAP_MS = 8 * 60_000
export const DAILY_BASE_SECS = 600
export const DAILY_MIN_CREDITS = 50
export const REBRAND_CP_DIVISOR = 1e8
export const REBRAND_CP_EXP = 0.45
export const CP_MULT_PER_POINT = 0.02
export const RP_MULT_PER_POINT = 0.01
export const ACHIEVEMENT_MULT = 0.01
export const TIER_UPGRADE_THRESHOLDS = [1, 10, 25, 50] as const
export const TIER_UPGRADE_COST_MULT = [10, 100, 1_000, 10_000] as const
export const TIER_UPGRADE_EFFECT = 2
