#!/usr/bin/env node
/**
 * Regenerate CHANGELOG.md from src/data/patchNotes.ts, the one place patch notes are written.
 *
 *   pnpm notes          rewrite CHANGELOG.md
 *   pnpm notes --check   exit 1 if it is out of date (what the test and CI use)
 *
 * The file is read with a tiny parser rather than imported, so this runs on plain node with no
 * build step and no TypeScript loader. The shape it expects is the one the data file already has:
 * an exported PATCH_NOTES array of object literals with string fields and a `changes` array.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const SOURCE = 'src/data/patchNotes.ts'
const OUT = 'CHANGELOG.md'
const LABELS = { added: 'Added', changed: 'Changed', balance: 'Balance', fixed: 'Fixed' }
const ORDER = ['added', 'changed', 'balance', 'fixed']

/** Every `field: 'value'` pair in a block, single or double quoted, escapes unwrapped. */
function fields(block) {
  const out = {}
  for (const m of block.matchAll(/(\w+):\s*'((?:[^'\\]|\\.)*)'/g)) out[m[1]] = m[2].replace(/\\'/g, "'").replace(/\\\\/g, '\\')
  return out
}

export function readNotes(source = SOURCE) {
  const src = readFileSync(source, 'utf8')
  const start = src.indexOf('export const PATCH_NOTES')
  if (start < 0) throw new Error(`${source}: no PATCH_NOTES export`)
  const body = src.slice(start)
  const notes = []
  // Each note starts at a `version:` line; the changes live between `changes: [` and its `]`.
  const blocks = body.split(/\n  \{\n/).slice(1)
  for (const block of blocks) {
    const head = block.split('changes:')[0] ?? ''
    const meta = fields(head)
    if (!meta.version) continue
    const changesRaw = block.slice(block.indexOf('changes:'))
    const changes = []
    for (const m of changesRaw.matchAll(/\{\s*kind:\s*'(\w+)',\s*text:\s*'((?:[^'\\]|\\.)*)'\s*\}/g)) {
      changes.push({ kind: m[1], text: m[2].replace(/\\'/g, "'").replace(/\\\\/g, '\\') })
    }
    notes.push({ version: meta.version, date: meta.date, kind: meta.kind, title: meta.title, summary: meta.summary, changes })
  }
  if (notes.length === 0) throw new Error(`${source}: parsed no notes`)
  return notes
}

export function renderChangelog(notes) {
  const lines = [
    '# Changelog',
    '',
    `Generated from \`${SOURCE}\` by \`pnpm notes\`. Do not edit this file by hand: add the entry to`,
    'the data file and regenerate, so the game and the repo always say the same thing.',
    '',
    'Versions are semver. A release bumps the minor, a hotfix bumps the patch, and the major stays',
    'at 0 until the game is feature complete. See `docs/RELEASING.md`.',
  ]
  for (const note of notes) {
    lines.push('', `## ${note.version} · ${note.title}`, '', `${note.kind === 'hotfix' ? 'Hotfix' : 'Release'} · ${note.date}`)
    if (note.summary) lines.push('', note.summary)
    for (const kind of ORDER) {
      const rows = note.changes.filter((c) => c.kind === kind)
      if (rows.length === 0) continue
      lines.push('', `### ${LABELS[kind]}`, '')
      for (const row of rows) lines.push(`- ${row.text}`)
    }
  }
  return `${lines.join('\n')}\n`
}

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/^.*[/\\]/, ''))
if (isMain) {
  const notes = readNotes()
  const next = renderChangelog(notes)
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(OUT, 'utf8')
    } catch {
      /* missing file counts as out of date */
    }
    if (current !== next) {
      console.error(`${OUT} is out of date. Run: pnpm notes`)
      process.exit(1)
    }
    console.log(`${OUT} is up to date (${notes.length} entries, newest ${notes[0].version})`)
  } else {
    writeFileSync(OUT, next)
    console.log(`wrote ${OUT}: ${notes.length} entries, newest ${notes[0].version}`)
  }
}
