/**
 * Patch notes, newest first. The one source of truth for "what changed and when".
 *
 * Three things read this file: the in-game Patch Notes modal, `CHANGELOG.md` (regenerated by
 * `pnpm notes`, never edited by hand) and `patchNotes.test.ts`, which pins the shape and keeps
 * `version` in step with `package.json`. Adding a release means adding an entry at the top and
 * running `pnpm notes`; the process lives in `docs/RELEASING.md`.
 *
 * Writing rules, because these are read by players and not by the person who wrote the code:
 *  - say what changed for the player, not which module moved
 *  - numbers over adjectives: "0.954 back on the credit", not "rebalanced"
 *  - one line per change, no trailing period, no em-dashes (the UI separator is `·`)
 */

/** A normal release, or a fix shipped on its own between releases. */
export type PatchKind = 'release' | 'hotfix'

/** The four buckets a change can land in. They print in this order. */
export type ChangeKind = 'added' | 'changed' | 'balance' | 'fixed'

export interface PatchChange {
  kind: ChangeKind
  text: string
}

export interface PatchNote {
  /** Semver, matching `package.json` for the newest entry. */
  version: string
  /** UTC calendar day, `YYYY-MM-DD`. */
  date: string
  kind: PatchKind
  /** Short headline, sentence case, no version number in it. */
  title: string
  /** One dry line under the headline. Optional for a hotfix. */
  summary?: string
  changes: PatchChange[]
}

/** Human labels for the buckets. */
export const CHANGE_LABELS: Record<ChangeKind, string> = {
  added: 'Added',
  changed: 'Changed',
  balance: 'Balance',
  fixed: 'Fixed',
}

/** The order buckets print in, in the game and in the changelog. */
export const CHANGE_ORDER: readonly ChangeKind[] = ['added', 'changed', 'balance', 'fixed']

export const PATCH_NOTES: readonly PatchNote[] = [
  {
    version: '0.2.5',
    date: '2026-09-14',
    kind: 'hotfix',
    title: 'Checkpoints on shelves',
    summary: 'The Models tab picks a kind instead of making you scroll past every image model to reach Audio.',
    changes: [
      { kind: 'changed', text: 'Models are split into Image, Video, 3D, Audio and API nodes, one shelf at a time, with the count on each chip' },
      { kind: 'changed', text: 'A kind you have never seen gets a dot, so your first video model announces itself instead of waiting to be scrolled past' },
      { kind: 'fixed', text: 'Anything that points you at one model, the level-up card, a lock hint, the Studio model list, now opens the shelf that model is on' },
    ],
  },
  {
    version: '0.2.4',
    date: '2026-09-14',
    kind: 'hotfix',
    title: 'New face on the button',
    changes: [
      { kind: 'changed', text: 'The Generate button wears the Comfy mark on its own instead of the blue tile. The header, the map and the splash keep the tile' },
    ],
  },
  {
    version: '0.2.3',
    date: '2026-09-14',
    kind: 'hotfix',
    title: 'Readable and pressable',
    summary: 'Text wraps instead of stopping at an ellipsis, and the logo admits it is a button.',
    changes: [
      { kind: 'fixed', text: 'Store text was cut off at one line, and 10 of the 38 upgrade descriptions did not fit in one. Descriptions, blurbs, model names, lock reasons and the Next up rows all wrap now' },
      { kind: 'changed', text: 'The Comfy logo answers a hover and a keyboard focus, and it carries the same tooltip as the Generate pill, which says the two are one button' },
      { kind: 'changed', text: 'A save with no clicks on it yet shows a ring around the logo until the first press' },
      { kind: 'changed', text: 'The tour used to ring the logo on its own, which taught that the pill was something else. It rings both and says so' },
    ],
  },
  {
    version: '0.2.2',
    date: '2026-09-14',
    kind: 'hotfix',
    title: 'The Lounge in one screen',
    summary: 'The bet button moved up beside the amount, and the coin waits to land before it says how it went.',
    changes: [
      { kind: 'fixed', text: 'The coin flip played its win or loss sound the moment you pressed the button, 0.9 s before the coin landed. The press is now a soft toss and the result sounds when the face shows' },
      { kind: 'fixed', text: 'Same on the wheel: the sampler ticks while the seed scrambles, the payoff sounds when it settles, and the reel turns during the scramble instead of after it' },
      { kind: 'fixed', text: 'The bank line, the pity pips, the pot and the win flash all moved the moment you bet. They hold still now until the coin or the seed lands' },
      { kind: 'changed', text: 'The loss sting was mastered about 13 dB louder than the win chime. It sits at the same level now, in the Lounge and on a ratioed post, and the flop sting comes down with it' },
      { kind: 'changed', text: 'The bet button sits beside the amount, so nothing needs a scroll to bet. Both tables fit one laptop screen: the wheel keeps its odds beside the seed and the coin sits next to its own line' },
    ],
  },
  {
    version: '0.2.1',
    date: '2026-09-14',
    kind: 'hotfix',
    title: 'Two dead ends',
    summary: 'The breaker banner now sells you the supply, and the save key stops stacking cards.',
    changes: [
      { kind: 'fixed', text: 'Buy a PSU did nothing from inside the Power tab. The tripped banner now lists the supplies on sale and you buy one from it' },
      { kind: 'added', text: 'Each supply in the banner says what it adds and whether it clears the breaker on its own' },
      { kind: 'fixed', text: 'Pressing S repeatedly stacked a new toast per press. One card now stays up and its timer extends three seconds past the last press' },
    ],
  },
  {
    version: '0.2.0',
    date: '2026-09-14',
    kind: 'release',
    title: 'The Latent Lounge',
    summary: 'Two tables, a breaker that means it, and people running your workflows.',
    changes: [
      { kind: 'added', text: 'The Latent Lounge, which is Seed Roulette with a clearer name and a second table' },
      { kind: 'added', text: 'Coin flip: your side pays double at 48%, the Comfy side takes the stake at 52%' },
      { kind: 'added', text: 'A bet slider and a number box that always agree, plus Min, Half, Double, 25%, 50% and All in' },
      { kind: 'added', text: 'Citizens: publish a workflow and invented players start running it, paying you the usual 5% royalty' },
      { kind: 'added', text: 'A board on /hub showing who ran what, what it paid and how much interest is left' },
      { kind: 'changed', text: 'Bets are priced in credits. No more 30s / 1m / 5m presets and no spin cooldown' },
      { kind: 'changed', text: 'Pressing S has an eight second cooldown. Autosave is untouched' },
      { kind: 'balance', text: 'The wheel pays back 0.954 on the credit, down from 1.038 when the cooldown was doing the work' },
      { kind: 'balance', text: 'A tripped breaker now stops every rig instead of scaling income down. Clicks still pay' },
      { kind: 'balance', text: 'A published workflow pays about 43 seconds of income over 43 minutes, then goes cold' },
    ],
  },
]

/** The version the game is running, which is the newest entry. */
export const GAME_VERSION: string = PATCH_NOTES[0]?.version ?? '0.0.0'
