/**
 * Patch notes, newest first. The one source of truth for "what changed and when".
 *
 * Three things read this file: the in-game Patch Notes modal, `CHANGELOG.md` (regenerated by
 * `pnpm notes`, never edited by hand) and `patchNotes.test.ts`, which pins the shape and keeps
 * `version` in step with `package.json`. Adding a release means adding an entry at the top and
 * running `pnpm notes`; the process lives in `docs/RELEASING.md`.
 *
 * Writing rules, because these are read by players and not by the person who wrote the code:
 *  - say what changed for the player, not which module moved
 *  - numbers over adjectives: "0.954 back on the credit", not "rebalanced"
 *  - one line per change, no trailing period, no em-dashes (the UI separator is `·`)
 */

/** A normal release, or a fix shipped on its own between releases. */
export type PatchKind = 'release' | 'hotfix'

/** The four buckets a change can land in. They print in this order. */
export type ChangeKind = 'added' | 'changed' | 'balance' | 'fixed'

export interface PatchChange {
  kind: ChangeKind
  text: string
}

export interface PatchNote {
  /** Semver, matching `package.json` for the newest entry. */
  version: string
  /** UTC calendar day, `YYYY-MM-DD`. */
  date: string
  kind: PatchKind
  /** Short headline, sentence case, no version number in it. */
  title: string
  /** One dry line under the headline. Optional for a hotfix. */
  summary?: string
  changes: PatchChange[]
}

/** Human labels for the buckets. */
export const CHANGE_LABELS: Record<ChangeKind, string> = {
  added: 'Added',
  changed: 'Changed',
  balance: 'Balance',
  fixed: 'Fixed',
}

/** The order buckets print in, in the game and in the changelog. */
export const CHANGE_ORDER: readonly ChangeKind[] = ['added', 'changed', 'balance', 'fixed']

export const PATCH_NOTES: readonly PatchNote[] = [
  {
    version: '0.2.0',
    date: '2026-09-14',
    kind: 'release',
    title: 'The Latent Lounge',
    summary: 'Two tables, a breaker that means it, and people running your workflows.',
    changes: [
      { kind: 'added', text: 'The Latent Lounge, which is Seed Roulette with a clearer name and a second table' },
      { kind: 'added', text: 'Coin flip: your side pays double at 48%, the Comfy side takes the stake at 52%' },
      { kind: 'added', text: 'A bet slider and a number box that always agree, plus Min, Half, Double, 25%, 50% and All in' },
      { kind: 'added', text: 'Citizens: publish a workflow and invented players start running it, paying you the usual 5% royalty' },
      { kind: 'added', text: 'A board on /hub showing who ran what, what it paid and how much interest is left' },
      { kind: 'changed', text: 'Bets are priced in credits. No more 30s / 1m / 5m presets and no spin cooldown' },
      { kind: 'changed', text: 'Pressing S has an eight second cooldown. Autosave is untouched' },
      { kind: 'balance', text: 'The wheel pays back 0.954 on the credit, down from 1.038 when the cooldown was doing the work' },
      { kind: 'balance', text: 'A tripped breaker now stops every rig instead of scaling income down. Clicks still pay' },
      { kind: 'balance', text: 'A published workflow pays about 43 seconds of income over 43 minutes, then goes cold' },
    ],
  },
]

/** The version the game is running, which is the newest entry. */
export const GAME_VERSION: string = PATCH_NOTES[0]?.version ?? '0.0.0'
